version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: chore
      include: scope
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
